// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfd_LZmoKvN2adkZpvqllY2OqYycEWxo',
    appId: '1:1025475050051:web:08a17e2fe60d7a5186f2f6',
    messagingSenderId: '1025475050051',
    projectId: 'kyumail-407810',
    authDomain: 'kyumail-407810.firebaseapp.com',
    storageBucket: 'kyumail-407810.appspot.com',
    measurementId: 'G-0S4819YS8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEePR-4jRpoN-d42F8foEs6Ldd4eLZjiQ',
    appId: '1:1025475050051:android:6a19d61450eae11d86f2f6',
    messagingSenderId: '1025475050051',
    projectId: 'kyumail-407810',
    storageBucket: 'kyumail-407810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBa2US_9P4od5FPRPhs_jEDeK2kmuLx_4',
    appId: '1:1025475050051:ios:fd8bcda13927970986f2f6',
    messagingSenderId: '1025475050051',
    projectId: 'kyumail-407810',
    storageBucket: 'kyumail-407810.appspot.com',
    androidClientId: '1025475050051-dvhj8lgs05lfu257s62p9u7vqe9d5nh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyuMail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBa2US_9P4od5FPRPhs_jEDeK2kmuLx_4',
    appId: '1:1025475050051:ios:69f75b23e6c01cc586f2f6',
    messagingSenderId: '1025475050051',
    projectId: 'kyumail-407810',
    storageBucket: 'kyumail-407810.appspot.com',
    androidClientId: '1025475050051-dvhj8lgs05lfu257s62p9u7vqe9d5nh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyuMail.RunnerTests',
  );
}
