# Generated by Django 5.0 on 2023-12-15 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reqid', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaseTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField(default=0)),
                ('sbase', models.CharField(max_length=1000)),
                ('rbase', models.CharField(max_length=1000)),
                ('sendbits', models.CharField(default='', max_length=1000)),
                ('key', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('dateofsend', models.DateField(default=datetime.datetime(2023, 12, 15, 23, 36, 44, 618843))),
                ('timeofsend', models.TimeField(default=datetime.datetime(2023, 12, 15, 23, 36, 44, 618843))),
                ('replto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('passtoken', models.CharField(default='', max_length=10)),
                ('currIP', models.CharField(default='0.0.0.0', max_length=50)),
                ('isOnline', models.IntegerField(default=0)),
                ('keys', models.IntegerField(default=100)),
            ],
        ),
    ]
