# Generated by Django 5.0 on 2023-12-16 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.BinaryField(default=b'\x00'),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='dateofsend',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 14, 31, 57, 820330)),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='timeofsend',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 14, 31, 57, 820330)),
        ),
    ]
