# Generated by Django 5.0 on 2023-12-16 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapis', '0002_attachments_file_alter_requesttemp_dateofsend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemp',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='dateofsend',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 0, 47, 157321)),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='timeofsend',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 15, 0, 47, 157321)),
        ),
    ]
