# Generated by Django 5.0 on 2023-12-16 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapis', '0004_user_image_alter_requesttemp_dateofsend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttemp',
            name='dateofsend',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 7, 8, 919599)),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='timeofsend',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 15, 7, 8, 919599)),
        ),
    ]
