# Generated by Django 5.0 on 2023-12-16 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapis', '0006_alter_requesttemp_dateofsend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField(default=0)),
                ('recemail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='dateofsend',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 39, 48, 415448)),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='timeofsend',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 15, 39, 48, 415448)),
        ),
    ]
