# Generated by Django 5.0 on 2023-12-16 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapis', '0009_alter_requesttemp_dateofsend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='dateofsend',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 44, 59, 313948)),
        ),
        migrations.AlterField(
            model_name='requesttemp',
            name='timeofsend',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 15, 44, 59, 313948)),
        ),
    ]
